/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : testclass
 * Author          : <YourName>
 * Created Date    : Feb 18, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Feb 18, 2026
 * Description     : This class implements for......
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Feb 18, 2026  │ <YourName>   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

public class testclass {

	@AuraEnabled(cacheable=true)
	public static void doSomething() {
		// Your logic here
	}

}